name: PonyLSP CI

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: linux-amd64
          # - os: windows-latest
          #   asset_name: windows-amd64
          # - os: macos-latest
          #   asset_name: macos-amd64

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      id: location
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT
        echo "PONY_VERSION=$PONY_VERSION" >> $GITHUB_OUTPUT
        echo "SHA=`echo $GITHUB_SHA | cut -c 1-5`" >> $GITHUB_OUTPUT
        echo "OS=${{matrix.os}}" >> $GITHUB_OUTPUT

    - name: Install libressl
      if: ${{ contains(matrix.os, 'macos') }}
      run: |
        brew update
        brew install libressl

    - name: Build.sh
      if: ${{ !contains(matrix.os, 'windows') }}
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE && bash build_ci.sh

    - name: Build.ps1
      if: ${{ contains(matrix.os, 'windows') }}
      shell: pwsh
      run: |
        Set-Location $Env:GITHUB_WORKSPACE
        .\build_ci.ps1

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.location.outputs.SHA }}
        files: |
          client_vscode/*.vsix