name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: build
      run: cd $GITHUB_WORKSPACE && bash build.sh

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: /home/runner/work/pony-language-server/pony-language-server/client_vscode/pony-lsp-1.0.0.vsix
        asset_name: vscode_pony-lsp-1.0.0.vsix
        tag: ${{ github.ref }}
        overwrite: true
        body: "VSCode extension"
