name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: ponyc
      run: cd $GITHUB_WORKSPACE && cd ponyc && make libs && make configure config=debug && make build config=debug

    - name: build
      run: cd $GITHUB_WORKSPACE && bash build.sh
